const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Text,
		C3.Plugins.List,
		C3.Plugins.Button,
		C3.Plugins.Arr,
		C3.Plugins.HTMLElement,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.UpdateHTML,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.HTMLElement.Acts.SetContent,
		C3.Plugins.Text.Exps.AsHTML,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.事件表2_Event2,
		C3.Plugins.List.Exps.SelectedText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.JavaScriptInEvents.事件表2_Event10,
		C3.JavaScriptInEvents.事件表2_Event15
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{內文: 0},
	{列表: 0},
	{下一個: 0},
	{上一個: 0},
	{台詞: 0},
	{陣列: 0},
	{標題: 0},
	{時間: 0},
	{HTML: 0},
	{輸入框: 0},
	{列表2: 0},
	{控制: 0},
	{階段: 0},
	{XX: 0},
	{YY: 0},
	{是否上: 0},
	{minu: 0},
	{stage: 0},
	{hour: 0},
	{變數: 0},
	{模式: 0},
	{數值: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	內文: class extends self.ITextInstance {},
	列表: class extends self.IListInstance {},
	下一個: class extends self.IButtonInstance {},
	上一個: class extends self.IButtonInstance {},
	台詞: class extends self.IButtonInstance {},
	陣列: class extends self.IArrayInstance {},
	標題: class extends self.ITextInstance {},
	時間: class extends self.ITextInstance {},
	HTML: class extends self.IHTMLElementInstance {},
	輸入框: class extends self.ITextInputInstance {},
	列表2: class extends self.IListInstance {},
	控制: class extends self.IButtonInstance {}
}